name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
env:
  # Unified API URLs (used across Newman & Dredd)
  API_URL: "https://api.isst.dev/tst"
  AUTH_URL: "https://auth.isst.dev/realms/bradford_realm/protocol/openid-connect/token"

jobs:
  deploy:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: read

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v5
      
      - name: Set API outputs
        id: set-api-url
        run: |
          echo ${API_URL}
          echo ${{ env.API_URL }}
          echo "api-url=${API_URL}" >> $GITHUB_OUTPUT
          echo "auth-url=${AUTH_URL}" >> $GITHUB_OUTPUT
     
    
  # Newman-test-api:
  #   name: Newman
  #   uses: ./.github/workflows/newman.yml
  #   permissions:                    
  #     security-events: write
  #   with:
  #     api-doc-url: 'https://api.isst.dev/tst'
  #     auth-url: 'https://auth.isst.dev/realms/bradford_realm/protocol/openid-connect/token'
  #   secrets:  
  #     api-username: ${{ secrets.API_USERNAME }}
  #     api-password: ${{ secrets.API_PASSWORD }}  
  
  dredd-tst:
    name: Contract Test (Dredd)
    uses: ./.github/workflows/dredd.yml
    permissions:                    
       actions: read
    with:
      url: ${{ needs.deploy.outputs.api-url }}
      auth-url: 'https://auth.isst.dev/realms/bradford_realm/protocol/openid-connect/token'
    secrets:
      api-username: ${{ secrets.API_USERNAME }}
      api-password: ${{ secrets.API_PASSWORD }}
  # build-and-test:
  #   name: Build and Test
  #   uses: ./.github/workflows/build.yml
  #   permissions:                    
  #     actions: read
  #     contents: read
  #     security-events: write
  #   with:
  #     node-version: '20.x'
  #     postgres-version: '15-alpine'
  #     docker-image-name: 'fullstack-app'

  # Trivy-scan:
  #   name: Trivy Scan
  #   needs: build-and-test
  #   uses: ./.github/workflows/trivy-scan.yml
  #   permissions:                   
      
  #     security-events: write
  #   with:
  #     docker-image-name: 'fullstack-app'
  #     scan-severity: 'HIGH,CRITICAL'
  #     fail-on-severity: false
  
  # zizmor-scan:
  #       name: Zizmor Scan
  #       needs: Newman-test-api
  #       #needs: build-and-test
  #       uses: ./.github/workflows/zizmor-scan.yml
  #       permissions:
  #         contents: read
  #         security-events: write