name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  Newman-test-api:
    name: Newman
    uses: ./.github/workflows/newman.yml
    permissions:                    
      security-events: write
    with:
      api-doc-url: 'https://api.isst.dev/tst'
      auth-url: 'https://auth.isst.dev/realms/bradford_realm/protocol/openid-connect/token'
      api-username: ${{ secrets.API_USERNAME }}
      api-password: ${{ secrets.API_PASSWORD }}  
        
  # build-and-test:
  #   name: Build and Test
  #   uses: ./.github/workflows/build.yml
  #   permissions:                    
  #     actions: read
  #     contents: read
  #     security-events: write
  #   with:
  #     node-version: '20.x'
  #     postgres-version: '15-alpine'
  #     docker-image-name: 'fullstack-app'

  # Trivy-scan:
  #   name: Trivy Scan
  #   needs: build-and-test
  #   uses: ./.github/workflows/trivy-scan.yml
  #   permissions:                   
      
  #     security-events: write
  #   with:
  #     docker-image-name: 'fullstack-app'
  #     scan-severity: 'HIGH,CRITICAL'
  #     fail-on-severity: false
  
  zizmor-scan:
        name: Zizmor Scan
        needs: Newman-test-api
        #needs: build-and-test
        uses: ./.github/workflows/zizmor-scan.yml
        permissions:
          contents: read
          security-events: write